@rootURL = http://localhost:5266


GET {{rootURL}}/locallore/
Accept: application/json

###
GET {{rootURL}}/api/users
Accept: application/json

###
GET GET {{rootURL}}/api/users/1
Accept: application/json




